name: Build Project
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build